#!/bin/bash -l
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=12:00:00
#SBATCH --job-name=naca-0012-34
#SBATCH --ntasks-per-node=2

module load singularity/3.6.0rc2
module load mpi/openmpi/4.0.1/cuda_aware_gcc_6.3.0

mkdir -p run
cp -r test_cases/naca0012-34-block-Ma-0.85 run/
cd run/naca0012-34-block-Ma-0.85
./Allrun 2
