#!/bin/bash -l
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --job-name=na12
#SBATCH --ntasks-per-node=16

module load singularity/3.6.0rc2
module load mpi/openmpi/4.0.1/cuda_aware_gcc_6.3.0

mkdir -p run
cp -r test_cases/Set1_iddes_a2_3D_alpha-4 run/
cd run/Set1_iddes_a2_3D_alpha-4
./Allrun 16
