#!/bin/bash -l
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --job-name=na12
#SBATCH --ntasks-per-node=8

module load singularity/3.6.0rc2
module load mpi/openmpi/4.0.1/cuda_aware_gcc_6.3.0

mkdir -p run
cp -r test_cases/old_base_NTR_Y40k run/
cd run/old_base_NTR_Y40k
./Allrun 8
