#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication surfaceTransformPoints -rotate-angle "((0 0 1) -5.0)" constant/triSurface/naca0012-34.stl constant/triSurface/naca0012-34-5.stl

#------------------------------------------------------------------------------